#ifndef _CUSTOM_MODELS_H_
#define _CUSTOM_MODELS_H_

void CustomModel_EditHeartContainerToDoubleDefense(void* heartContainerCMB);
void CustomModel_EditFairyOcarinaToZeldasLullaby(void* fairyOcarinaCMB);
void CustomModel_EditFairyOcarinaToSariasSong(void* fairyOcarinaCMB);
void CustomModel_EditFairyOcarinaToSunsSong(void* fairyOcarinaCMB);
void CustomModel_EditFairyOcarinaToEponasSong(void* fairyOcarinaCMB);
void CustomModel_EditFairyOcarinaToSongOfStorms(void* fairyOcarinaCMB);
void CustomModel_EditFairyOcarinaToSongOfTime(void* fairyOcarinaCMB);
void CustomModel_EditOcarinaOfTimeToMinuetOfForest(void* ocarinaOfTimeCMB);
void CustomModel_EditOcarinaOfTimeToBoleroOfFire(void* ocarinaOfTimeCMB);
void CustomModel_EditOcarinaOfTimeToSerenadeOfWater(void* ocarinaOfTimeCMB);
void CustomModel_EditOcarinaOfTimeToRequiemOfSpirit(void* ocarinaOfTimeCMB);
void CustomModel_EditOcarinaOfTimeToNocturneOfShadow(void* ocarinaOfTimeCMB);
void CustomModel_EditOcarinaOfTimeToPreludeOfLight(void* ocarinaOfTimeCMB);

#endif //_CUSTOM_MODELS_H_
