#ifndef _MENUS_H_
#define _MENUS_H_

typedef struct MenuSpriteManager {
    char unk_00[0x474];
} MenuSpriteManager; // size = 0x474

typedef enum {
    GEARSLOT_KOKIRI_SWORD,
    GEARSLOT_MASTER_SWORD,
    GEARSLOT_BIGGORON_SWORD,
    GEARSLOT_DEKU_SHIELD,
    GEARSLOT_HYLIAN_SHIELD,
    GEARSLOT_MIRROR_SHIELD,
    GEARSLOT_KOKIRI_TUNIC,
    GEARSLOT_GORON_TUNIC,
    GEARSLOT_ZORA_TUNIC,
    GEARSLOT_FOREST_MEDALLION,
    GEARSLOT_FIRE_MEDALLION,
    GEARSLOT_WATER_MEDALLION,
    GEARSLOT_SPIRIT_MEDALLION,
    GEARSLOT_SHADOW_MEDALLION,
    GEARSLOT_LIGHT_MEDALLION,
    GEARSLOT_KOKIRI_EMERALD,
    GEARSLOT_GORON_RUBY,
    GEARSLOT_ZORA_SAPPHIRE,
    GEARSLOT_OCARINA,
    GEARSLOT_SHARD_OF_AGONY,
    GEARSLOT_GERUDO_TOKEN,
    GEARSLOT_SKULL_TOKEN,
    GEARSLOT_QUIVER_BULLET_BAG,
    GEARSLOT_BOMB_BAG,
    GEARSLOT_STRENGTH_UPGRADE,
    GEARSLOT_SCALE,
    GEARSLOT_HEART_PIECE,
} GearMenuSlot;

#endif //_MENUS_H_
