#ifndef _Z3DACTOR_ID_H_
#define _Z3DACTOR_ID_H_

enum ActorId {
    ACTOR_STALFOS            = 0x002,
    ACTOR_POE                = 0x00D,
    ACTOR_OCTOROK            = 0x00E,
    ACTOR_WALLMASTER         = 0x011,
    ACTOR_DODONGO            = 0x012,
    ACTOR_KEESE              = 0x013,
    ACTOR_TEKTITE            = 0x01B,
    ACTOR_LEEVER             = 0x01C,
    ACTOR_PEAHAT             = 0x01D,
    ACTOR_LIZALFOS           = 0x025,
    ACTOR_GOHMA_LARVA        = 0x02B,
    ACTOR_SHABOM             = 0x02D,
    ACTOR_BABY_DODONGO       = 0x02F,
    ACTOR_DARK_LINK          = 0x033,
    ACTOR_BIRI               = 0x034,
    ACTOR_TAILPASARAN        = 0x035,
    ACTOR_SKULLTULA          = 0x037,
    ACTOR_TORCH_SLUG         = 0x038,
    ACTOR_STINGER_FLOOR      = 0x03A,
    ACTOR_MOBLIN             = 0x04B,
    ACTOR_ARMOS              = 0x054,
    ACTOR_DEKU_BABA          = 0x055,
    ACTOR_MAD_SCRUB          = 0x060,
    ACTOR_BARI               = 0x063,
    ACTOR_BUBBLE             = 0x069,
    ACTOR_FLYING_FLOOR_TILE  = 0x06B,
    ACTOR_BEAMOS             = 0x08A,
    ACTOR_FLOORMASTER        = 0x08E,
    ACTOR_REDEAD             = 0x090,
    ACTOR_POE_SISTER         = 0x091,
    ACTOR_SKULLWALLTULA      = 0x095,
    ACTOR_FLARE_DANCER       = 0x099,
    ACTOR_FLARE_DANCER_FLAME = 0x0A3,
    ACTOR_DEAD_HAND          = 0x0A4,
    ACTOR_DEAD_HAND_HAND     = 0x0A5,
    ACTOR_ENEMY_SPAWNER      = 0x0A7,
    ACTOR_SHELL_BLADE        = 0x0C5,
    ACTOR_BIG_OCTO           = 0x0C6,
    ACTOR_WITHERED_DEKU_BABA = 0x0C7,
    ACTOR_LIKE_LIKE          = 0x0DD,
    ACTOR_PARASITIC_TENTACLE = 0x0DE,
    ACTOR_ANUBIS             = 0x0E0,
    ACTOR_SPIKE              = 0x0EC,
    ACTOR_ANUBIS_SPAWNER     = 0x0F6,
    ACTOR_IRON_KNUCKLE       = 0x113,
    ACTOR_SKULL_KID          = 0x115,
    ACTOR_FLYING_POT         = 0x11D,
    ACTOR_FREEZARD           = 0x121,
    ACTOR_STINGER_WATER      = 0x18C,
    ACTOR_GERUDO_FIGHTER     = 0x197,
    ACTOR_WOLFOS             = 0x1AF,
    ACTOR_STALCHILD          = 0x1B0,
    ACTOR_GUAY               = 0x1C0,
    ACTOR_MAX                = 0x1DB,
};

#endif //_Z3DACTOR_ID_H_
