#include "s_enemy_souls.h"
#include "s_scene_id.h"

const char* const smallKeyStringForest  = "Forest Temple Small Key";
const char* const smallKeyStringFire    = "Fire Temple Small Key";
const char* const smallKeyStringWater   = "Water Temple Small Key";
const char* const smallKeyStringSpirit  = "Spirit Temple Small Key";
const char* const smallKeyStringShadow  = "Shadow Temple Small Key";
const char* const smallKeyStringBotW    = "Bottom of the Well Small Key";
const char* const smallKeyStringGTG     = "Training Grounds Small Key";
const char* const smallKeyStringHideout = "Gerudo Fortress Small Key";
const char* const smallKeyStringGanon   = "Ganon's Castle Small Key";
const char* const smallKeyStringGame    = "Chest Game Small Key";

const char* const keyRingStringForest  = "Forest Temple Key Ring";
const char* const keyRingStringFire    = "Fire Temple Key Ring";
const char* const keyRingStringWater   = "Water Temple Key Ring";
const char* const keyRingStringSpirit  = "Spirit Temple Key Ring";
const char* const keyRingStringShadow  = "Shadow Temple Key Ring";
const char* const keyRingStringBotW    = "Bottom of the Well Key Ring";
const char* const keyRingStringGTG     = "Training Grounds Key Ring";
const char* const keyRingStringHideout = "Gerudo Fortress Key Ring";
const char* const keyRingStringGanon   = "Ganon's Castle Key Ring";

// This array is included in the patch side for the enemy souls page in the in-game menu,
// and in the app side for the starting inventory options.
SoulMenuInfo SoulMenuNames[SOUL_MAX] = {
    // Normal enemies, ordered alphabetically
    { SOUL_ANUBIS, "Anubis" },
    { SOUL_ARMOS, "Armos" },
    { SOUL_BEAMOS, "Beamos" },
    { SOUL_BIRI_BARI, "Biri, Bari" },
    { SOUL_BUBBLE, "Bubble (all)" },
    { SOUL_DARK_LINK, "Dark Link" },
    { SOUL_DEAD_HAND, "Dead Hand" },
    { SOUL_DEKU_BABA, "Deku Baba (all)" },
    { SOUL_DEKU_SCRUB, "Deku Scrub (all)" },
    { SOUL_DOOR_MIMIC, "Door Mimic" },
    { SOUL_FLARE_DANCER, "Flare Dancer" },
    { SOUL_FLYING_TRAP, "Flying Pot & Tile" },
    { SOUL_FREEZARD, "Freezard" },
    { SOUL_GERUDO, "Gerudo, Iron Knuckles" },
    { SOUL_GUAY, "Guay" },
    { SOUL_KEESE, "Keese (all)" },
    { SOUL_LEEVER, "Leever" },
    { SOUL_LIKE_LIKE, "Like Like" },
    { SOUL_LIZALFOS, "Lizalfos, Dinolfos" },
    { SOUL_MOBLIN, "Moblin, Club Moblin" },
    { SOUL_OCTOROK, "Octorok, Big Octo" },
    { SOUL_TENTACLE, "Parasitic Tentacle" },
    { SOUL_PEAHAT, "Peahat" },
    { SOUL_POE, "Poe (all)" },
    { SOUL_REDEAD_GIBDO, "ReDead, Gibdo" },
    { SOUL_SHABOM, "Shabom" },
    { SOUL_SHELL_BLADE, "Shell Blade" },
    { SOUL_SKULL_KID, "Skull Kid" },
    { SOUL_SKULLTULA, "Skulltula (all)" },
    { SOUL_SPIKE, "Spike" },
    { SOUL_STALCHILD, "Stalchild" },
    { SOUL_STALFOS, "Stalfos" },
    { SOUL_STINGER, "Stinger" },
    { SOUL_TAILPASARAN, "Tailpasaran" },
    { SOUL_TEKTITE, "Tektite" },
    { SOUL_TORCH_SLUG, "Torch Slug" },
    { SOUL_WALLMASTER, "Wallmaster, Floormaster" },
    { SOUL_WOLFOS, "Wolfos (all)" },
    // Bosses
    { SOUL_GOHMA, "Gohma, Gohma Larva", "Queen Gohma" },
    { SOUL_DODONGO, "Dodongo (all)", "King Dodongo" },
    { SOUL_BARINADE, "Barinade" },
    { SOUL_PHANTOM_GANON, "Phantom Ganon" },
    { SOUL_VOLVAGIA, "Volvagia" },
    { SOUL_MORPHA, "Morpha" },
    { SOUL_BONGO_BONGO, "Bongo Bongo" },
    { SOUL_TWINROVA, "Twinrova" },
    { SOUL_GANON, "Ganondorf, Ganon" },
};

const char* const SceneNames[SCENE_MAX] = {
    [SCENE_DEKU_TREE]                      = "Deku Tree",
    [SCENE_DODONGOS_CAVERN]                = "Dodongo's Cavern",
    [SCENE_JABU_JABU]                      = "Jabu Jabu's Belly",
    [SCENE_FOREST_TEMPLE]                  = "Forest Temple",
    [SCENE_FIRE_TEMPLE]                    = "Fire Temple",
    [SCENE_WATER_TEMPLE]                   = "Water Temple",
    [SCENE_SPIRIT_TEMPLE]                  = "Spirit Temple",
    [SCENE_SHADOW_TEMPLE]                  = "Shadow Temple",
    [SCENE_BOTTOM_OF_THE_WELL]             = "Bottom of the Well",
    [SCENE_ICE_CAVERN]                     = "Ice Cavern",
    [SCENE_GANONS_TOWER]                   = "Ganon's Tower",
    [SCENE_GERUDO_TRAINING_GROUND]         = "Gerudo Training Grounds",
    [SCENE_THIEVES_HIDEOUT]                = "Thieves' Hideout",
    [SCENE_INSIDE_GANONS_CASTLE]           = "Inside Ganon's Castle",
    [SCENE_GANONS_TOWER_COLLAPSE_INTERIOR] = "Ganon's Tower (Collapsing)",
    [SCENE_INSIDE_GANONS_CASTLE_COLLAPSE]  = "Inside Ganon's Castle (Collapsing)",
    [SCENE_TREASURE_BOX_SHOP]              = "Treasure Chest Shop",
    [SCENE_DEKU_TREE_BOSS]                 = "Queen Gohma's Lair",
    [SCENE_DODONGOS_CAVERN_BOSS]           = "King Dodongo's Lair",
    [SCENE_JABU_JABU_BOSS]                 = "Barinade's Lair",
    [SCENE_FOREST_TEMPLE_BOSS]             = "Phantom Ganon's Lair",
    [SCENE_FIRE_TEMPLE_BOSS]               = "Volvagia's Lair",
    [SCENE_WATER_TEMPLE_BOSS]              = "Morpha's Lair",
    [SCENE_SPIRIT_TEMPLE_BOSS]             = "Twinrova's Lair",
    [SCENE_SHADOW_TEMPLE_BOSS]             = "Bongo Bongo's Lair",
    [SCENE_GANONDORF_BOSS]                 = "Ganondorf's Lair",
    [SCENE_GANONS_TOWER_COLLAPSE_EXTERIOR] = "Ganon's Tower Exterior (Collapsing)",
    [SCENE_MARKET_ENTRANCE_DAY]            = "Market Entrance (Child - Day)",
    [SCENE_MARKET_ENTRANCE_NIGHT]          = "Market Entrance (Child - Night)",
    [SCENE_MARKET_ENTRANCE_RUINS]          = "Market Entrance (Ruins)",
    [SCENE_BACK_ALLEY_DAY]                 = "Back Alley (Child - Day)",
    [SCENE_BACK_ALLEY_NIGHT]               = "Back Alley (Child - Night)",
    [SCENE_MARKET_DAY]                     = "Market (Child - Day)",
    [SCENE_MARKET_NIGHT]                   = "Market (Child - Night)",
    [SCENE_MARKET_RUINS]                   = "Market (Ruins)",
    [SCENE_TEMPLE_OF_TIME_EXTERIOR_DAY]    = "Temple of Time Exterior (Child - Day)",
    [SCENE_TEMPLE_OF_TIME_EXTERIOR_NIGHT]  = "Temple of Time Exterior (Child - Night)",
    [SCENE_TEMPLE_OF_TIME_EXTERIOR_RUINS]  = "Temple of Time Exterior (Ruins)",
    [SCENE_KNOW_IT_ALL_BROS_HOUSE]         = "Know-It-All Brothers' House",
    [SCENE_TWINS_HOUSE]                    = "House of Twins",
    [SCENE_MIDOS_HOUSE]                    = "Mido's House",
    [SCENE_SARIAS_HOUSE]                   = "Saria's House",
    [SCENE_KAKARIKO_CENTER_GUEST_HOUSE]    = "Carpenter Boss's House",
    [SCENE_BACK_ALLEY_HOUSE]               = "Back Alley House (Man in Green)",
    [SCENE_BAZAAR]                         = "Bazaar",
    [SCENE_KOKIRI_SHOP]                    = "Kokiri Shop",
    [SCENE_GORON_SHOP]                     = "Goron Shop",
    [SCENE_ZORA_SHOP]                      = "Zora Shop",
    [SCENE_POTION_SHOP_KAKARIKO]           = "Kakariko Potion Shop",
    [SCENE_POTION_SHOP_MARKET]             = "Market Potion Shop",
    [SCENE_BOMBCHU_SHOP]                   = "Bombchu Shop",
    [SCENE_HAPPY_MASK_SHOP]                = "Happy Mask Shop",
    [SCENE_LINKS_HOUSE]                    = "Link's House",
    [SCENE_DOG_LADY_HOUSE]                 = "Back Alley House (Dog Lady)",
    [SCENE_STABLE]                         = "Stable",
    [SCENE_IMPAS_HOUSE]                    = "Impa's House",
    [SCENE_LAKESIDE_LABORATORY]            = "Lakeside Laboratory",
    [SCENE_CARPENTERS_TENT]                = "Carpenters' Tent",
    [SCENE_GRAVEKEEPERS_HUT]               = "Gravekeeper's Hut",
    [SCENE_GREAT_FAIRYS_FOUNTAIN_MAGIC]    = "Great Fairy's Fountain (Upgrades)",
    [SCENE_FAIRYS_FOUNTAIN]                = "Fairy's Fountain",
    [SCENE_GREAT_FAIRYS_FOUNTAIN_SPELLS]   = "Great Fairy's Fountain (Spells)",
    [SCENE_GROTTOS]                        = "Grottos",
    [SCENE_REDEAD_GRAVE]                   = "Grave (Redead)",
    [SCENE_GRAVE_WITH_FAIRYS_FOUNTAIN]     = "Grave (Fairy's Fountain)",
    [SCENE_ROYAL_FAMILYS_TOMB]             = "Royal Family's Tomb",
    [SCENE_SHOOTING_GALLERY]               = "Shooting Gallery",
    [SCENE_TEMPLE_OF_TIME]                 = "Temple of Time",
    [SCENE_CHAMBER_OF_THE_SAGES]           = "Chamber of the Sages",
    [SCENE_CASTLE_COURTYARD_GUARDS_DAY]    = "Castle Hedge Maze (Day)",
    [SCENE_CASTLE_COURTYARD_GUARDS_NIGHT]  = "Castle Hedge Maze (Night)",
    [SCENE_CUTSCENE_MAP]                   = "Cutscene Map",
    [SCENE_WINDMILL_AND_DAMPES_GRAVE]      = "Dampe's Grave / Windmill",
    [SCENE_FISHING_POND]                   = "Fishing Pond",
    [SCENE_CASTLE_COURTYARD_ZELDA]         = "Castle Courtyard",
    [SCENE_BOMBCHU_BOWLING_ALLEY]          = "Bombchu Bowling Alley",
    [SCENE_LON_LON_BUILDINGS]              = "Ranch Buildings",
    [SCENE_MARKET_GUARD_HOUSE]             = "Guard House",
    [SCENE_POTION_SHOP_GRANNY]             = "Granny's Potion Shop",
    [SCENE_GANON_BOSS]                     = "Ganon's Battle Arena",
    [SCENE_HOUSE_OF_SKULLTULA]             = "House of Skulltula",
    [SCENE_HYRULE_FIELD]                   = "Hyrule Field",
    [SCENE_KAKARIKO_VILLAGE]               = "Kakariko Village",
    [SCENE_GRAVEYARD]                      = "Graveyard",
    [SCENE_ZORAS_RIVER]                    = "Zora's River",
    [SCENE_KOKIRI_FOREST]                  = "Kokiri Forest",
    [SCENE_SACRED_FOREST_MEADOW]           = "Sacred Forest Meadow",
    [SCENE_LAKE_HYLIA]                     = "Lake Hylia",
    [SCENE_ZORAS_DOMAIN]                   = "Zora's Domain",
    [SCENE_ZORAS_FOUNTAIN]                 = "Zora's Fountain",
    [SCENE_GERUDO_VALLEY]                  = "Gerudo Valley",
    [SCENE_LOST_WOODS]                     = "Lost Woods",
    [SCENE_DESERT_COLOSSUS]                = "Desert Colossus",
    [SCENE_GERUDOS_FORTRESS]               = "Gerudo's Fortress",
    [SCENE_HAUNTED_WASTELAND]              = "Haunted Wasteland",
    [SCENE_HYRULE_CASTLE]                  = "Hyrule Castle",
    [SCENE_DEATH_MOUNTAIN_TRAIL]           = "Death Mountain Trail",
    [SCENE_DEATH_MOUNTAIN_CRATER]          = "Death Mountain Crater",
    [SCENE_GORON_CITY]                     = "Goron City",
    [SCENE_LON_LON_RANCH]                  = "Lon Lon Ranch",
    [SCENE_OUTSIDE_GANONS_CASTLE]          = "Outside Ganon's Castle",
    [SCENE_65]                             = "",
    [SCENE_66]                             = "",
    [SCENE_67]                             = "",
    [SCENE_68]                             = "",
    [SCENE_69]                             = "",
    [SCENE_6A]                             = "",
    [SCENE_HYRULE_FIELD_TITLE_SCREEN]      = "",
};
