name: Code Linting

env:
  # These are used automatically by git
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_AUTHOR_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub Actions
  GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

jobs:
  auto-formatter:
    name: Auto Format Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2

    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: "./code ./source ./shared"
        extensions: 'h,cpp,c,hpp'
        clangFormatVersion: 14
        style: file
        inplace: True

    - name: Add and commit
      run: |
        git add --all
        if ! git diff --cached --quiet; then
          git commit -m "Auto-format code to match clang rules"
          git push
        fi
